name: Build 3DSX App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20250101
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Compile 3DSX App
        run: |
          # Create symbolic link to map standard build paths
          ln -s /opt/devkitpro /usr/local/share/devkitpro
          
          # Compile the main C code object
          arm-none-eabi-gcc -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O2 -mword-relocations -fomit-frame-pointer -ffast-math -I/opt/devkitpro/libctru/include -D__3DS__ -c source/main.c -o main.o
          
          # Link object files into a 3DS executable ELF binary
          arm-none-eabi-gcc -specs=3dsx.specs -g -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft main.o -L/opt/devkitpro/libctru/lib -lctru -lm -o widescreen_toggle.elf
          
          # Convert the ELF binary into your usable 3DSX app file
          /opt/devkitpro/tools/bin/3dsxtool widescreen_toggle.elf widescreen_toggle.3dsx
          
      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: WidescreenToggle-3DSX
          path: '*.3dsx'
